INSERT INTO bibliotecaOnline.usuarios (email, nombre, passwd) VALUES
('mateussousa@gmail.com', 'Matheus', '$2y$10$zR38vqb4Hro5drWEUl/k8e.KwD7DPyWmy3WXoOBBjjDEiRsxq/hdC'),
('gabriel@informatica.com', 'Gabriel', '$2y$10$VrWlYeDID0ZKPW8XmyR91uFxlupisT1WrAg/QlEhyL9l120SXX/GS'),
('pepe@gmail.com', 'Pepe', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC');

INSERT INTO bibliotecaOnline.juegos (titulo, descripcion, autor, caratula, categoria, enlace, ano, propietario) VALUES
('Minecraft', 'Juego de mundo abierto donde puedes construir, explorar y sobrevivir en mundos generados aleatoriamente.', 'Mojang Studios', '../../Imgs/Caratulas_Juegos_Ejemplo/Minecraft.jpg', 'Sandbox', 'https://www.minecraft.net/', 2011, 'mateussousa@gmail.com'),
('The Legend of Zelda: Breath of the Wild', 'Aventura de mundo abierto donde Link explora Hyrule para derrotar a Ganon.', 'Nintendo', '../../Imgs/Caratulas_Juegos_Ejemplo/Zelda_Botw.jpg', 'Aventura', 'https://www.zelda.com/breath-of-the-wild/', 2017, 'mateussousa@gmail.com'),
('Fortnite', 'Juego multijugador de disparos y construcción con modos Battle Royale y Creativo.', 'Epic Games', '../../Imgs/Caratulas_Juegos_Ejemplo/Fortnite.jpg', 'Acción', 'https://www.epicgames.com/fortnite/', 2017, 'mateussousa@gmail.com'),
('Grand Theft Auto V', 'Juego de acción y mundo abierto ambientado en la ciudad ficticia de Los Santos.', 'Rockstar Games', '../../Imgs/Caratulas_Juegos_Ejemplo/GTA_V.jpg', 'Acción', 'https://www.rockstargames.com/V/', 2013, 'mateussousa@gmail.com'),
('Roblox', 'Plataforma de juegos en línea que permite a los usuarios crear y jugar en experiencias creadas por otros jugadores.', 'Roblox Corporation', '../../Imgs/Caratulas_Juegos_Ejemplo/Roblox.jpg', 'Sandbox', 'https://www.roblox.com/', 2006, 'mateussousa@gmail.com'),
('Overwatch', 'Shooter en primera persona basado en equipos, con héroes únicos y habilidades especiales.', 'Blizzard Entertainment', '../../Imgs/Caratulas_Juegos_Ejemplo/Overwatch.jpg', 'Shooter', 'https://overwatch.blizzard.com/', 2016, 'mateussousa@gmail.com'),
('Among Us', 'Juego multijugador en línea donde los jugadores deben descubrir quién es el impostor dentro de una nave espacial.', 'Innersloth', '../../Imgs/Caratulas_Juegos_Ejemplo/Among_Us.jpg', 'Casual', 'https://www.innersloth.com/games/among-us/', 2018, 'mateussousa@gmail.com'),
('Call of Duty: Warzone', 'Shooter en primera persona ambientado en un entorno de batalla masiva con hasta 150 jugadores.', 'Infinity Ward', '../../Imgs/Caratulas_Juegos_Ejemplo/Warzone.jpg', 'Shooter', 'https://www.callofduty.com/warzone', 2020, 'mateussousa@gmail.com'),
('Super Mario Galaxy', 'Juego de plataformas 3D donde Mario explora planetas en el espacio para rescatar a la princesa Peach.', 'Nintendo', '../../Imgs/Caratulas_Juegos_Ejemplo/Mario_Galaxy.jpg', 'Plataformas', 'https://www.nintendo.com/es-es/Juegos/Wii/Super-Mario-Galaxy-283721.html', 2007, 'mateussousa@gmail.com'),
('Super Mario Odyssey', 'Juego de plataformas en 3D donde Mario viaja por diferentes mundos para rescatar a Peach.', 'Nintendo', '../../Imgs/Caratulas_Juegos_Ejemplo/Mario_Odyssey.jpg', 'Plataformas', 'https://www.nintendo.com/es-es/Juegos/Nintendo-Switch/Super-Mario-Odyssey-1173339.html', 2017, 'mateussousa@gmail.com');
