INSERT INTO bibliotecaOnline.usuarios (email, nombre, passwd, foto) VALUES
('usuario1@example.com', 'Usuario Uno', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario2@example.com', 'Usuario Dos', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario3@example.com', 'Usuario Tres', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario4@example.com', 'Usuario Cuatro', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario5@example.com', 'Usuario Cinco', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario6@example.com', 'Usuario Seis', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario7@example.com', 'Usuario Siete', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario8@example.com', 'Usuario Ocho', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario9@example.com', 'Usuario Nueve', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario10@example.com', 'Usuario Diez', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario11@example.com', 'Usuario Once', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario12@example.com', 'Usuario Doce', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario13@example.com', 'Usuario Trece', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario14@example.com', 'Usuario Catorce', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario15@example.com', 'Usuario Quince', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario16@example.com', 'Usuario Dieciseis', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario17@example.com', 'Usuario Diecisiete', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario18@example.com', 'Usuario Dieciocho', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario19@example.com', 'Usuario Diecinueve', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario20@example.com', 'Usuario Veinte', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario21@example.com', 'Usuario Veintiuno', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario22@example.com', 'Usuario Veintidos', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario23@example.com', 'Usuario Veintitres', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario24@example.com', 'Usuario Veinticuatro', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png'),
('usuario25@example.com', 'Usuario Veinticinco', '$2y$10$0H.AYMe9BBxvxxkzKLfR3.mnt.FY38xaWLABJi5LDHWWhVswOfWnC', '../../Imgs/Fotos_Perfil/Foto_Base.png');

INSERT INTO bibliotecaOnline.votos (email, id, voto) VALUES
-- Juego 1: Minecraft (MUY POSITIVO: 22 Likes, 3 Dislikes)
('usuario1@example.com', 1, 1),
('usuario2@example.com', 1, 1),
('usuario3@example.com', 1, 1),
('usuario4@example.com', 1, 1),
('usuario5@example.com', 1, 1),
('usuario6@example.com', 1, 1),
('usuario7@example.com', 1, 1),
('usuario8@example.com', 1, 1),
('usuario9@example.com', 1, 1),
('usuario10@example.com', 1, 1),
('usuario11@example.com', 1, 1),
('usuario12@example.com', 1, 1),
('usuario13@example.com', 1, 1),
('usuario14@example.com', 1, 1),
('usuario15@example.com', 1, 1),
('usuario16@example.com', 1, 1),
('usuario17@example.com', 1, 1),
('usuario18@example.com', 1, 1),
('usuario19@example.com', 1, 1),
('usuario20@example.com', 1, 1),
('usuario21@example.com', 1, 1),
('usuario22@example.com', 1, 1),
('usuario23@example.com', 1, 0),
('usuario24@example.com', 1, 0),
('usuario25@example.com', 1, 0),

-- Juego 2: Zelda: BotW (MUY POSITIVO: 23 Likes, 2 Dislikes)
('usuario1@example.com', 2, 1),
('usuario2@example.com', 2, 1),
('usuario3@example.com', 2, 1),
('usuario4@example.com', 2, 1),
('usuario5@example.com', 2, 1),
('usuario6@example.com', 2, 1),
('usuario7@example.com', 2, 1),
('usuario8@example.com', 2, 1),
('usuario9@example.com', 2, 1),
('usuario10@example.com', 2, 1),
('usuario11@example.com', 2, 1),
('usuario12@example.com', 2, 1),
('usuario13@example.com', 2, 1),
('usuario14@example.com', 2, 1),
('usuario15@example.com', 2, 1),
('usuario16@example.com', 2, 1),
('usuario17@example.com', 2, 1),
('usuario18@example.com', 2, 1),
('usuario19@example.com', 2, 1),
('usuario20@example.com', 2, 1),
('usuario21@example.com', 2, 1),
('usuario22@example.com', 2, 1),
('usuario23@example.com', 2, 1),
('usuario24@example.com', 2, 0),
('usuario25@example.com', 2, 0),

-- Juego 3: Fortnite (MUY NEGATIVO/POLÉMICO: 5 Likes, 20 Dislikes)
('usuario1@example.com', 3, 1),
('usuario2@example.com', 3, 1),
('usuario3@example.com', 3, 1),
('usuario4@example.com', 3, 1),
('usuario5@example.com', 3, 1),
('usuario6@example.com', 3, 0),
('usuario7@example.com', 3, 0),
('usuario8@example.com', 3, 0),
('usuario9@example.com', 3, 0),
('usuario10@example.com', 3, 0),
('usuario11@example.com', 3, 0),
('usuario12@example.com', 3, 0),
('usuario13@example.com', 3, 0),
('usuario14@example.com', 3, 0),
('usuario15@example.com', 3, 0),
('usuario16@example.com', 3, 0),
('usuario17@example.com', 3, 0),
('usuario18@example.com', 3, 0),
('usuario19@example.com', 3, 0),
('usuario20@example.com', 3, 0),
('usuario21@example.com', 3, 0),
('usuario22@example.com', 3, 0),
('usuario23@example.com', 3, 0),
('usuario24@example.com', 3, 0),
('usuario25@example.com', 3, 0),

-- Juego 4: GTA V (POSITIVO: 18 Likes, 7 Dislikes)
('usuario1@example.com', 4, 1),
('usuario2@example.com', 4, 1),
('usuario3@example.com', 4, 1),
('usuario4@example.com', 4, 1),
('usuario5@example.com', 4, 1),
('usuario6@example.com', 4, 1),
('usuario7@example.com', 4, 1),
('usuario8@example.com', 4, 1),
('usuario9@example.com', 4, 1),
('usuario10@example.com', 4, 1),
('usuario11@example.com', 4, 1),
('usuario12@example.com', 4, 1),
('usuario13@example.com', 4, 1),
('usuario14@example.com', 4, 1),
('usuario15@example.com', 4, 1),
('usuario16@example.com', 4, 1),
('usuario17@example.com', 4, 1),
('usuario18@example.com', 4, 1),
('usuario19@example.com', 4, 0),
('usuario20@example.com', 4, 0),
('usuario21@example.com', 4, 0),
('usuario22@example.com', 4, 0),
('usuario23@example.com', 4, 0),
('usuario24@example.com', 4, 0),
('usuario25@example.com', 4, 0),

-- Juego 5: Roblox (NEUTRAL/NEGATIVO: 10 Likes, 15 Dislikes)
('usuario1@example.com', 5, 1),
('usuario2@example.com', 5, 1),
('usuario3@example.com', 5, 1),
('usuario4@example.com', 5, 1),
('usuario5@example.com', 5, 1),
('usuario6@example.com', 5, 1),
('usuario7@example.com', 5, 1),
('usuario8@example.com', 5, 1),
('usuario9@example.com', 5, 1),
('usuario10@example.com', 5, 1),
('usuario11@example.com', 5, 0),
('usuario12@example.com', 5, 0),
('usuario13@example.com', 5, 0),
('usuario14@example.com', 5, 0),
('usuario15@example.com', 5, 0),
('usuario16@example.com', 5, 0),
('usuario17@example.com', 5, 0),
('usuario18@example.com', 5, 0),
('usuario19@example.com', 5, 0),
('usuario20@example.com', 5, 0),
('usuario21@example.com', 5, 0),
('usuario22@example.com', 5, 0),
('usuario23@example.com', 5, 0),
('usuario24@example.com', 5, 0),
('usuario25@example.com', 5, 0),

-- Juego 6: Overwatch (POSITIVO: 19 Likes, 6 Dislikes)
('usuario1@example.com', 6, 1),
('usuario2@example.com', 6, 1),
('usuario3@example.com', 6, 1),
('usuario4@example.com', 6, 1),
('usuario5@example.com', 6, 1),
('usuario6@example.com', 6, 1),
('usuario7@example.com', 6, 1),
('usuario8@example.com', 6, 1),
('usuario9@example.com', 6, 1),
('usuario10@example.com', 6, 1),
('usuario11@example.com', 6, 1),
('usuario12@example.com', 6, 1),
('usuario13@example.com', 6, 1),
('usuario14@example.com', 6, 1),
('usuario15@example.com', 6, 1),
('usuario16@example.com', 6, 1),
('usuario17@example.com', 6, 1),
('usuario18@example.com', 6, 1),
('usuario19@example.com', 6, 1),
('usuario20@example.com', 6, 0),
('usuario21@example.com', 6, 0),
('usuario22@example.com', 6, 0),
('usuario23@example.com', 6, 0),
('usuario24@example.com', 6, 0),
('usuario25@example.com', 6, 0),

-- Juego 7: Among Us (MUY NEGATIVO: 4 Likes, 21 Dislikes)
('usuario1@example.com', 7, 1),
('usuario2@example.com', 7, 1),
('usuario3@example.com', 7, 1),
('usuario4@example.com', 7, 1),
('usuario5@example.com', 7, 0),
('usuario6@example.com', 7, 0),
('usuario7@example.com', 7, 0),
('usuario8@example.com', 7, 0),
('usuario9@example.com', 7, 0),
('usuario10@example.com', 7, 0),
('usuario11@example.com', 7, 0),
('usuario12@example.com', 7, 0),
('usuario13@example.com', 7, 0),
('usuario14@example.com', 7, 0),
('usuario15@example.com', 7, 0),
('usuario16@example.com', 7, 0),
('usuario17@example.com', 7, 0),
('usuario18@example.com', 7, 0),
('usuario19@example.com', 7, 0),
('usuario20@example.com', 7, 0),
('usuario21@example.com', 7, 0),
('usuario22@example.com', 7, 0),
('usuario23@example.com', 7, 0),
('usuario24@example.com', 7, 0),
('usuario25@example.com', 7, 0),

-- Juego 8: Warzone (NEUTRAL/POSITIVO: 15 Likes, 10 Dislikes)
('usuario1@example.com', 8, 1),
('usuario2@example.com', 8, 1),
('usuario3@example.com', 8, 1),
('usuario4@example.com', 8, 1),
('usuario5@example.com', 8, 1),
('usuario6@example.com', 8, 1),
('usuario7@example.com', 8, 1),
('usuario8@example.com', 8, 1),
('usuario9@example.com', 8, 1),
('usuario10@example.com', 8, 1),
('usuario11@example.com', 8, 1),
('usuario12@example.com', 8, 1),
('usuario13@example.com', 8, 1),
('usuario14@example.com', 8, 1),
('usuario15@example.com', 8, 1),
('usuario16@example.com', 8, 0),
('usuario17@example.com', 8, 0),
('usuario18@example.com', 8, 0),
('usuario19@example.com', 8, 0),
('usuario20@example.com', 8, 0),
('usuario21@example.com', 8, 0),
('usuario22@example.com', 8, 0),
('usuario23@example.com', 8, 0),
('usuario24@example.com', 8, 0),
('usuario25@example.com', 8, 0),

-- Juego 9: Super Mario Galaxy (MUY POSITIVO: 24 Likes, 1 Dislike)
('usuario1@example.com', 9, 1),
('usuario2@example.com', 9, 1),
('usuario3@example.com', 9, 1),
('usuario4@example.com', 9, 1),
('usuario5@example.com', 9, 1),
('usuario6@example.com', 9, 1),
('usuario7@example.com', 9, 1),
('usuario8@example.com', 9, 1),
('usuario9@example.com', 9, 1),
('usuario10@example.com', 9, 1),
('usuario11@example.com', 9, 1),
('usuario12@example.com', 9, 1),
('usuario13@example.com', 9, 1),
('usuario14@example.com', 9, 1),
('usuario15@example.com', 9, 1),
('usuario16@example.com', 9, 1),
('usuario17@example.com', 9, 1),
('usuario18@example.com', 9, 1),
('usuario19@example.com', 9, 1),
('usuario20@example.com', 9, 1),
('usuario21@example.com', 9, 1),
('usuario22@example.com', 9, 1),
('usuario23@example.com', 9, 1),
('usuario24@example.com', 9, 1),
('usuario25@example.com', 9, 0),

-- Juego 10: Super Mario Odyssey (MUY POSITIVO: 21 Likes, 4 Dislikes)
('usuario1@example.com', 10, 1),
('usuario2@example.com', 10, 1),
('usuario3@example.com', 10, 1),
('usuario4@example.com', 10, 1),
('usuario5@example.com', 10, 1),
('usuario6@example.com', 10, 1),
('usuario7@example.com', 10, 1),
('usuario8@example.com', 10, 1),
('usuario9@example.com', 10, 1),
('usuario10@example.com', 10, 1),
('usuario11@example.com', 10, 1),
('usuario12@example.com', 10, 1),
('usuario13@example.com', 10, 1),
('usuario14@example.com', 10, 1),
('usuario15@example.com', 10, 1),
('usuario16@example.com', 10, 1),
('usuario17@example.com', 10, 1),
('usuario18@example.com', 10, 1),
('usuario19@example.com', 10, 1),
('usuario20@example.com', 10, 1),
('usuario21@example.com', 10, 1),
('usuario22@example.com', 10, 0),
('usuario23@example.com', 10, 0),
('usuario24@example.com', 10, 0),
('usuario25@example.com', 10, 0);